import { fontVariables } from "@/styles/fonts";
import "./globals.css";
import LenisSmoothScroll from "@/components/LenisSmoothScroll";


export const metadata = {
  title: "RTX-4080",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontVariables.combined} antialiased`}
      >
        <LenisSmoothScroll />
        {children}
      </body>
    </html>
  );
}
